[package]
name = "message-signing-example"
version = "0.1.0"
edition = "2018"

[dependencies]
emurgo-message-signing = { "path" = "../../rust" }
cardano-serialization-lib = { "path" = "../../../cardano-serialization-lib/rust" }
